version:  2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Clone DumprX
          command: |
            git clone https://github.com/DumprX/DumprX DumprX
      - run:
          name: Setup DumprX's Environment
          command: |
            sudo bash setup.sh
            sudo apt install -y f2fs-tools
            git config --global user.name "Souhrud"
            git config --global user.email "souhrud@live.com"
            ROM_URL=$(grep -oP 'ROM_URL = "\K[^"]*' Dump)
      - run:
          name: Setup Config envs
          command: |
            echo "$GITLAB_TOKEN" > .gitlab_token  # Only for Gitlab
            echo "$GITLAB_GROUP" > .gitlab_group  # Only for Gitlab
            echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa  # Only for Gitlab
            echo "$BOT_TOKEN" > .tg_token
            echo "$CHAT_ID" > .tg_chat
            chmod  600 ~/.ssh/id_rsa
      - run:
          name: Run the Extra Command
          command: |
            $EXTRA_CMD
      - run:
          name: Start Dumping
          command: |
            ./dumper.sh "$ROM_URL"
